# Глава 2 Массив последовательностей

## Общие сведения о встроенных последовательностях

#### Пример 2.1. Построить список кодовых позиций Unicode по строке

In [1]:
symbols = '@#$%^&'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[64, 35, 36, 37, 94, 38]

#### Пример 2.2. Построить список кодовых позиций Unicode по строке с применением listcomp

In [2]:
symbols = '@#$%^&'
codes = [ord(symbol) for symbol in symbols]
codes

[64, 35, 36, 37, 94, 38]

#### Локальная область видимости внутри включений и генераторных выражений

In [3]:
x = 'ABC'
codes = [ord(x) for x in x]
x

'ABC'

In [4]:
codes

[65, 66, 67]

In [5]:
codes = [last := ord(c) for c in x]
last

67

In [6]:
c

NameError: name 'c' is not defined

#### Пример 2.3. Один и тот же список, построенный с помощью listcomp и композиции map и filter

In [7]:
beyond_ascii = [ord(s) for s in symbols if ord(s) < 90]
beyond_ascii

[64, 35, 36, 37, 38]

In [8]:
beyond_ascii = list(filter(lambda c: c < 90, map(ord, symbols)))
beyond_ascii

[64, 35, 36, 37, 38]

#### Пример 2.4. Построение декартова произведения с помощью спискового включения

In [11]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [12]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [13]:
tshirts = [(color, size) for size in sizes for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

#### Пример 2.5. Инициализация кортежа и массива с помощью генераторного выражения

In [14]:
symbols = '@#$%^&'
tuple(ord(symbol) for symbol in symbols)

(64, 35, 36, 37, 94, 38)

In [15]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [64, 35, 36, 37, 94, 38])

#### Пример 2.6. Порождение декартова произведения генераторным выражением

In [16]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in (f'{c} {s}' for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


#### Пример 2.7. Кортежи как записи

In [18]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [19]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


#### Кортежи как неизменяемые списки

In [20]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
a == b

True

In [21]:
b[-1].append(99)
a == b

False

In [22]:
b

(10, 'alpha', [1, 2, 99])

In [23]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

tf = (10, 'alpha', (1, 2))
tm = (10, 'alpha', [1, 2])
fixed(tf)

True

In [24]:
fixed(tm)

False

#### Распаковка последовательностей и итерируемых объектов

In [25]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude

33.9425

In [26]:
longitude

-118.408056

In [13]:
b, a = a, b

In [27]:
divmod(20, 8)

(2, 4)

In [28]:
t = (20, 8)
divmod(*t)

(2, 4)

In [29]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [17]:
import os
_, filename = os.path.split('home/luciano/.ssh/id_rsa.pub')
filename

'id_rsa.pub'

#### Использование * для выборки лишних элементов

In [19]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [20]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [21]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [22]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [23]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

#### Распаковка с помощью * в вызовах функций и литеральных последовательностях

In [24]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

fun (*[1, 2], 3, *range(4, 7))

(1, 2, 3, 4, (5, 6))

In [25]:
*range(4), 4

(0, 1, 2, 3, 4)

In [26]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [28]:
{*range(4), 4, *(5, 6, 7)}

{0, 1, 2, 3, 4, 5, 6, 7}

#### Пример 2.8. Распаковка вложенных кортежей для доступа к долготе

In [30]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_areas:
        if lon <= 0:
            print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')
if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


#### Пример 2.9. Метод из гипотетического класса Robot

In [3]:
def handle_message(self, message):
    match message:
        case['BEEPER', frequency, times]:
            self.beep(times, frequency)
        case['NECK', angle]:
            self.rotate_neck(angle)
        case['LED', ident, intensity]:
            self.leds[ident].set_brightness(ident, intensity)
        case['LED', ident, red, green, blue]:
            self.leds[ident].set_color(ident, red, green, blue)
        case _:
            raise InvalidCommand(message)

#### Пример 2.10. Деструктуризация вложенных кортежей (необходима версия Python ≥ 3.10)

In [6]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_areas:
        match record:
            case [name, _, _, (lat, lon)] if lon <= 0:
                print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')
if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
São Paulo       |  -23.5478 |  -46.6358


#### 2.11

In [ ]:
def evaluate(exp: Expression, env: Environment) -> Any:
    "Evaluate an expression in an environment."
    if isinstance(exp, Symbol): # ссылка на переменную
        return env[exp]
    # ... несколько строк опущено
    elif exp[0] == 'quote': # (quote exp)
        (_, x) = exp
        return x
    elif exp[0] == 'if': # (if test conseq alt)
        (_, test, consequence, alternative) = exp
        if evaluate(test, env):
            return evaluate(consequence, env)
        else:
            return evaluate(alternative, env)
    elif exp[0] == 'lambda': # (lambda (parm…) body…)
        (_, parms, *body) = exp
        return Procedure(parms, body, env)
    elif exp[0] == 'define':
        (_, name, value_exp) = exp
        env[name] = evaluate(value_exp, env)

#### 2.12

In [ ]:
def evaluate(exp: Expression, env: Environment) -> Any:
    "Evaluate an expression in an environment."
    match exp:
 # ... несколько строк опущено
        case ['quote', x]:
            return x
        case ['if', test, consequence, alternative]:
            if evaluate(test, env):
                return evaluate(consequence, env)
            else:
                return evaluate(alternative, env)
        case ['lambda', [*parms], *body] if body:
            return Procedure(parms, body, env)
        case ['define', Symbol() as name, value_exp]:
            env[name] = evaluate(value_exp, env)
        # ... еще несколько строк опущено
        case _:
            raise SyntaxError(lispstr(exp))

#### Почему в срезы и диапазоны не включается последний элемент

In [8]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [9]:
l[2:]

[30, 40, 50, 60]

In [10]:
l[3:]

[40, 50, 60]

In [11]:
l[:3]

[10, 20, 30]

#### Объекты среза

In [12]:
s = 'bicycle'
s[::3]

'bye'

In [13]:
s[::-1]

'elcycib'

In [14]:
s[::-2]

'eccb'

#### 2.13

In [15]:
 invoice = """
...
0.....6.................................40........52...55........
... 1909 Pimoroni PiBrella $17.50 3 $52.50
... 1489 6mm Tactile Switch x20 $4.95 2 $9.90
... 1510 Panavise Jr. - PV-201 $28.00 1 $28.00
... 1601 PiTFT Mini Kit 320x240 $34.95 1 $34.95
... """
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])


40........52 6.................................
 imoroni PiBrella $17.50 3 $52.50
0 mm Tactile Switch x20 $4.95 2 $9.9
00 anavise Jr. - PV-201 $28.00 1 $28.
.95 iTFT Mini Kit 320x240 $34.95 1 $34
 


#### Присваивание срезу

In [29]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [31]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [32]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [33]:
l[2:5] = 100

TypeError: can only assign an iterable

In [34]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

#### Использование + и * для последовательностей

In [35]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [36]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

#### Построение списка списков

#### 2.14

In [37]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [38]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [42]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [43]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

#### 2.15

In [39]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [40]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [44]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [45]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [46]:
l = [1, 2, 3]
id(l)

140090470152128

In [48]:
l *= 2
id(l)

140090470152128

In [49]:
t = (1, 2, 3)
id(t)

140090469788224

In [50]:
t *= 2
id(t)

140090458543520

#### Головоломка: присваивание A +=

#### 2.16, 2.17

In [51]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [52]:
t

(1, 2, [30, 40, 50, 60])

In [54]:
import dis
dis.dis('s[a] += b')

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


#### Метод list.sort и встроенная функция sorted

In [1]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [2]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [3]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [5]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [6]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [7]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [8]:
fruits.sort()

In [9]:
fruits

['apple', 'banana', 'grape', 'raspberry']

#### Массивы

In [7]:
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.7174710227762161

In [8]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [9]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [10]:
floats2[-1]

0.7174710227762161

In [11]:
floats2 == floats

True

#### Представление областей памяти

#### 2.20

In [1]:
from array import array
octets = array('B', range(6))
m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [2]:
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [3]:
m3 = m1.cast('B', [3, 2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [4]:
m2[1, 1] = 22
m3[1, 1] = 33
octets

array('B', [0, 1, 2, 33, 22, 5])

#### 2.21

In [5]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [6]:
memv[0]

-2

In [7]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [8]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

#### NumPy

#### 2.22

In [10]:
import numpy as np
a =  np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.shape

(12,)

In [13]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a[2]

array([ 8,  9, 10, 11])

In [15]:
a[2, 1]

9

In [16]:
a[:, 1]

array([1, 5, 9])

In [18]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Двусторонние и другие очереди

#### 2.23

In [34]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [35]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [36]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [37]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [38]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [39]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)